language: node_js
node_js:
  - 10
branches:
  only:
    - published

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

script:
  - npm run generate

deploy:
  provider: pages
  local-dir: dist
  repo: popcorn-quimper/popcorn-quimper.github.io
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: published
